"""One-button autonomous regression runner for Frame By Plane.

The runner executes destructive coverage only inside temporary Scenes and
restores the user's active Scene afterwards. It intentionally does not drive a
real save/reopen or Blender's global Undo stack from Python: both operations
replace or rewind Main and are unsafe while another operator is still running.
Those checks remain clearly listed in the final clipboard report.
"""

from __future__ import annotations

import binascii
import importlib
import platform
import shutil
import struct
import sys
import tempfile
import time
import tomllib
import traceback
import zlib
from datetime import datetime
from pathlib import Path

import bpy
from bpy.props import BoolProperty, FloatProperty, IntProperty, StringProperty
from bpy.types import Operator

from .constants import FBP_VERSION_STRING
from .diagnostics import (
    diagnostic_report_messages,
    diagnostic_report_status,
    write_diagnostic_report,
)
from .effects_registry import FBP_EFFECT_REGISTRY
from .layers import fbp_layer_backend_type, is_fbp_layer_object
from .runtime import (
    FBP_DATA_ERRORS,
    FBP_DATA_IO_ERRORS,
    fbp_runtime_set,
    fbp_warn,
)


_REPORT_NAME = "FBP_Developer_Test_Report"
_TEMP_SCENE_NAMES = (
    "FBP Developer Import Test",
    "FBP Native Regression",
    "FBP Effects Regression",
)
_INTERMEDIATE_REPORT_NAMES = (
    "FBP_Project_Health",
    "FBP_Effect_Control_Health",
    "FBP_Lifecycle_Audit",
    "FBP_Native_Regression_Scene_Report",
    "FBP_Native_Backend_Regression",
    "FBP_Effects_Regression_Report",
    "FBP_Effects_Contract_Audit",
    "FBP_Mask_Interaction_Audit",
    "FBP_Render_Contract_Audit",
    "FBP_Render_Parity_Audit",
    "FBP_Persistence_Audit",
    "FBP_Undo_Redo_Endurance",
    "FBP_Deep_Addon_Audit",
    "FBP_Effects_Profiler_Report",
    "FBP_Release_Gate",
)

# New data generated by the regression scenes is removed only when it did not
# exist before the run and has no remaining users. The order is deliberate.
_CLEANUP_COLLECTIONS = (
    "collections",
    "objects",
    "meshes",
    "curves",
    "lattices",
    "cameras",
    "lights",
    "materials",
    "node_groups",
    "images",
    "actions",
    "armatures",
    "grease_pencils_v3",
    "grease_pencils",
    "texts",
)

_MANUAL_CHECKS = (
    "Save the regression .blend, close it and reopen it, then run the Persistence verification requiring reopen.",
    "Perform real UI Undo and Redo operations and verify the captured endurance baseline; the global Undo stack is intentionally not driven from a running Python operator.",
    "Install and enable/disable the extension on every supported operating system and architecture.",
    "Import representative PSD/PSB, Procreate, Toon Boom and video files; bundled decoder availability is checked automatically, but external source fidelity needs real samples.",
    "Inspect visual output, Lattice deformation, camera framing, drag-and-drop, file-browser dialogs and raw pixel clipboard pasting interactively.",
    "Run a real background render process and verify cancellation/output paths on the target operating system.",
)


def _png_chunk(kind, payload):
    body = kind + payload
    return struct.pack(">I", len(payload)) + body + struct.pack(">I", binascii.crc32(body) & 0xFFFFFFFF)


def _write_test_png(filepath, phase=0):
    """Write a small deterministic RGBA PNG without external dependencies."""
    width, height = 24, 16
    rows = []
    phase = int(phase) % 255
    for y in range(height):
        row = bytearray((0,))
        for x in range(width):
            alpha = 255 if 2 <= x < width - 2 and 2 <= y < height - 2 else 0
            row.extend((
                (x * 11 + phase * 17) % 256,
                (y * 17 + phase * 29) % 256,
                ((x + y) * 7 + phase * 41) % 256,
                alpha,
            ))
        rows.append(bytes(row))
    raw = b"".join(rows)
    payload = (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
        + _png_chunk(b"IDAT", zlib.compress(raw, 9))
        + _png_chunk(b"IEND", b"")
    )
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)
    return str(path)


def _operator_callable(idname):
    namespace, name = str(idname).split(".", 1)
    return getattr(getattr(bpy.ops, namespace), name)


def _result_finished(result):
    try:
        return "FINISHED" in result
    except TypeError:
        return False


def _safe_text_string(text):
    try:
        return text.as_string() if text is not None else ""
    except FBP_DATA_ERRORS:
        return ""


def _id_pointer(value):
    try:
        return int(value.as_pointer())
    except (AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
        return id(value)


def _scene_rigs(scene):
    try:
        return tuple(obj for obj in scene.objects if is_fbp_layer_object(obj))
    except FBP_DATA_ERRORS:
        return ()


def _unique_scene_backup_name(base):
    stem = f"{base} · Preserved"
    name = stem
    index = 2
    while bpy.data.scenes.get(name) is not None:
        name = f"{stem} {index}"
        index += 1
    return name


def _tag_redraw():
    wm = getattr(bpy.context, "window_manager", None)
    if wm is None:
        return
    try:
        for window in tuple(wm.windows):
            screen = getattr(window, "screen", None)
            for area in tuple(getattr(screen, "areas", ()) or ()):
                area.tag_redraw()
    except FBP_DATA_ERRORS:
        pass


class FBP_OT_RunAutonomousDeveloperTest(Operator):
    bl_idname = "fbp.run_autonomous_developer_test"
    bl_label = "Developer Tool"
    bl_description = (
        "Run the autonomous Frame By Plane regression suite in temporary Scenes, "
        "restore the current project and copy one complete diagnostic report to the clipboard"
    )

    _timer = None
    _steps = None
    _step_index = 0
    _records = None
    _original_scene = None
    _original_active_object = None
    _original_selected_names = None
    _original_frame = 1
    _original_mode = "OBJECT"
    _start_time = 0.0
    _temp_paths = None
    _scene_backups = None
    _data_snapshot = None
    _report_snapshot = None
    _cancelled = False
    _operator_count = 0
    _effect_count = 0
    _poll_errors = None
    _finished = False

    @classmethod
    def poll(cls, context):
        wm = getattr(context, "window_manager", None)
        return bool(
            wm
            and getattr(context, "window", None) is not None
            and bool(getattr(wm, "fbp_developer_tool_unlocked", False))
            and not bool(getattr(wm, "fbp_developer_test_running", False))
        )

    def _record(self, name, status, summary, details=(), duration=0.0):
        status = str(status or "INFO").upper()
        if status not in {"PASS", "WARNING", "FAIL", "INFO", "MANUAL", "SKIP"}:
            status = "INFO"
        self._records.append({
            "name": str(name),
            "status": status,
            "summary": str(summary or ""),
            "details": tuple(str(item) for item in (details or ()) if str(item or "").strip()),
            "duration": max(0.0, float(duration or 0.0)),
        })

    def _run_operator(self, idname, **properties):
        started = time.perf_counter()
        try:
            # Disable the called operator's automatic undo entry. The test
            # runner owns cleanup and must not fill the user's Undo history
            # with temporary regression Scenes.
            result = _operator_callable(idname)("EXEC_DEFAULT", False, **properties)
            return _result_finished(result), result, "", time.perf_counter() - started
        except Exception as exc:
            return False, set(), f"{type(exc).__name__}: {exc}", time.perf_counter() - started

    def _capture_report(self, label, report_name, *, operator_ok=True, duration=0.0, info_is_pass=False):
        text = bpy.data.texts.get(report_name)
        report_status = diagnostic_report_status(text)
        messages = diagnostic_report_messages(text)
        content = _safe_text_string(text)
        if not operator_ok or text is None:
            status = "FAIL"
        elif report_status == "PASS":
            status = "PASS"
        elif report_status in {"WARNING", "FAIL"}:
            status = "FAIL" if "REVIEW REQUIRED" in content or ": FAIL" in content or ": ERROR" in content else "WARNING"
        elif info_is_pass and content.strip():
            status = "PASS"
        else:
            status = "WARNING"
        summary = f"{report_status.replace('_', ' ').title()} · {len(messages)} actionable message(s)"
        self._record(label, status, summary, messages[:80], duration)
        return status, content

    def _snapshot_data(self):
        snapshot = {}
        for name in ("scenes",) + _CLEANUP_COLLECTIONS:
            collection = getattr(bpy.data, name, None)
            if collection is None:
                continue
            try:
                snapshot[name] = {_id_pointer(item) for item in tuple(collection)}
            except (AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
                snapshot[name] = set()
        return snapshot

    def _snapshot_reports(self):
        snapshot = {}
        for name in _INTERMEDIATE_REPORT_NAMES:
            text = bpy.data.texts.get(name)
            if text is None:
                snapshot[name] = None
                continue
            try:
                fake_user = bool(text.use_fake_user)
            except FBP_DATA_ERRORS:
                fake_user = False
            snapshot[name] = (_safe_text_string(text), fake_user)
        return snapshot

    def _reserve_scene_names(self):
        self._scene_backups = []
        for name in _TEMP_SCENE_NAMES:
            scene = bpy.data.scenes.get(name)
            if scene is None:
                continue
            backup_name = _unique_scene_backup_name(name)
            scene.name = backup_name
            self._scene_backups.append((scene, name))

    def _initialize(self, context):
        wm = context.window_manager
        window = context.window
        self._timer = None
        self._cancelled = False
        self._finished = False
        self._records = []
        self._steps = ()
        self._step_index = 0
        self._temp_paths = []
        self._scene_backups = []
        self._data_snapshot = {}
        self._report_snapshot = {}
        self._poll_errors = []
        self._operator_count = 0
        self._effect_count = 0
        self._start_time = time.perf_counter()
        # Suspend all managed add-on timers before creating or removing any
        # temporary Scene graph. Modal event timers are separate and continue to
        # drive this operator's progress UI.
        fbp_runtime_set("fbp_pause_managed_timers", True)
        fbp_runtime_set("fbp_managed_timers_resume_after", 0.0)
        try:
            from .object_masks import clear_object_mask_runtime_cache
            clear_object_mask_runtime_cache()
        except (ImportError, AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
            pass
        try:
            from .safe_tasks import clear_scheduled
            clear_scheduled()
        except (ImportError, AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
            pass
        self._original_scene = window.scene
        self._original_frame = int(getattr(self._original_scene, "frame_current", 1) or 1)
        self._original_active_object = getattr(context.view_layer.objects, "active", None)
        self._original_selected_names = tuple(
            str(getattr(obj, "name", "") or "") for obj in tuple(getattr(context, "selected_objects", ()) or ())
        )
        self._original_mode = str(getattr(context, "mode", "OBJECT") or "OBJECT")
        try:
            if self._original_mode != "OBJECT" and bpy.ops.object.mode_set.poll():
                bpy.ops.object.mode_set(mode="OBJECT")
        except (AttributeError, RuntimeError):
            pass

        self._data_snapshot = self._snapshot_data()
        self._report_snapshot = self._snapshot_reports()
        self._reserve_scene_names()

        self._steps = (
            ("Preflight and registration", self._step_preflight),
            ("Import and creation smoke test", self._step_import_smoke),
            ("Import-scene contracts", self._step_import_contracts),
            ("Native regression scene", self._step_native_regression),
            ("Native persistence and parity", self._step_native_persistence_parity),
            ("Experimental compositor", self._step_compositor),
            ("Effects regression scene", self._step_effects_regression),
            ("Effects, masks and render contracts", self._step_effect_contracts),
            ("Performance profile", self._step_profile),
            ("Automated release gate", self._step_release_gate),
            ("Clipboard diagnostic path", self._step_clipboard_diagnostic),
        )
        self._step_index = 0

        wm.fbp_developer_tool_unlocked = False
        wm.fbp_developer_test_running = True
        wm.fbp_developer_test_progress = 0.0
        wm.fbp_developer_test_step = 0
        wm.fbp_developer_test_total = len(self._steps)
        wm.fbp_developer_test_status = "Preparing autonomous tests"
        wm.fbp_developer_test_last_status = "RUNNING"
        return True

    def invoke(self, context, _event):
        try:
            self._initialize(context)
            self._timer = context.window_manager.event_timer_add(0.08, window=context.window)
            context.window_manager.modal_handler_add(self)
        except Exception as exc:
            if self._records is not None:
                self._record(
                    "Developer Tool",
                    "FAIL",
                    f"Could not start Developer Tool: {type(exc).__name__}: {exc}",
                    (traceback.format_exc(),),
                )
                self._finish(context)
            else:
                context.window_manager.fbp_developer_test_running = False
            self.report({'ERROR'}, f"Could not start Developer Tool: {exc}")
            return {'CANCELLED'}
        _tag_redraw()
        return {'RUNNING_MODAL'}

    def execute(self, context):
        # Scripted/background calls use the same suite synchronously. The N-panel
        # button uses invoke/modal so progress remains visible between steps.
        try:
            self._initialize(context)
            while self._step_index < len(self._steps):
                self._run_next_step(context)
            self._finish(context)
            return {'FINISHED'}
        except Exception as exc:
            self._record("Developer Tool", "FAIL", f"Unhandled runner error: {exc}", (traceback.format_exc(),))
            self._finish(context)
            return {'CANCELLED'}

    def modal(self, context, event):
        if event.type == 'ESC':
            self._cancelled = True
            self._record("Developer Tool", "WARNING", "Cancelled by user; cleanup completed")
            self._finish(context)
            return {'CANCELLED'}
        if event.type != 'TIMER':
            return {'RUNNING_MODAL'}
        try:
            if self._step_index < len(self._steps):
                self._run_next_step(context)
                return {'RUNNING_MODAL'}
            self._finish(context)
            return {'FINISHED'}
        except Exception as exc:
            self._record(
                "Developer Tool",
                "FAIL",
                f"Unhandled runner error: {type(exc).__name__}: {exc}",
                (traceback.format_exc(),),
            )
            self._finish(context)
            return {'CANCELLED'}

    def _run_next_step(self, context):
        name, callback = self._steps[self._step_index]
        wm = context.window_manager
        wm.fbp_developer_test_step = self._step_index + 1
        wm.fbp_developer_test_status = name
        wm.fbp_developer_test_progress = self._step_index / max(1, len(self._steps))
        _tag_redraw()
        started = time.perf_counter()
        try:
            callback(context)
        except Exception as exc:
            self._record(
                name,
                "FAIL",
                f"Unhandled step error: {type(exc).__name__}: {exc}",
                (traceback.format_exc(),),
                time.perf_counter() - started,
            )
        self._step_index += 1
        wm.fbp_developer_test_progress = self._step_index / max(1, len(self._steps))
        _tag_redraw()

    def _step_preflight(self, context):
        started = time.perf_counter()
        details = [
            f"Blender: {bpy.app.version_string}",
            f"Frame By Plane: {FBP_VERSION_STRING}",
            f"Platform: {platform.platform()}",
            f"Python: {platform.python_version()}",
        ]
        failures = []
        warnings = []
        if tuple(bpy.app.version) < (5, 1, 2):
            failures.append("Blender 5.1.2 or newer is required")
        if getattr(context, "window", None) is None:
            failures.append("No interactive Blender window is available")

        package_prefix = str(__package__ or "")
        operator_ids = set()
        for module_name, module in tuple(sys.modules.items()):
            if not module or not (module_name == package_prefix or module_name.startswith(package_prefix + ".")):
                continue
            for value in tuple(vars(module).values()):
                if not isinstance(value, type):
                    continue
                try:
                    if not issubclass(value, Operator):
                        continue
                except TypeError:
                    continue
                idname = str(getattr(value, "bl_idname", "") or "")
                if idname.startswith("fbp."):
                    operator_ids.add(idname)

        missing = []
        poll_errors = []
        for idname in sorted(operator_ids):
            try:
                operator = _operator_callable(idname)
                operator.get_rna_type()
            except Exception as exc:
                missing.append(f"{idname}: {exc}")
                continue
            try:
                operator.poll()
            except Exception as exc:
                poll_errors.append(f"{idname}: {type(exc).__name__}: {exc}")
        self._operator_count = len(operator_ids)
        self._poll_errors = poll_errors
        details.append(f"Registered FBP operators discovered: {len(operator_ids)}")
        details.append(f"Operator poll exceptions: {len(poll_errors)}")
        if missing:
            failures.extend(f"Missing operator registration: {item}" for item in missing)
        if poll_errors:
            details.append("Poll exceptions are context-sensitive diagnostics and do not fail registration")
            details.extend(poll_errors[:30])

        self._effect_count = len(FBP_EFFECT_REGISTRY)
        details.append(f"Registered effects: {self._effect_count}")
        if self._effect_count <= 0:
            failures.append("The effect registry is empty")

        manifest_path = Path(__file__).with_name("blender_manifest.toml")
        try:
            manifest_data = tomllib.loads(manifest_path.read_text(encoding="utf-8"))
            manifest_version = str(manifest_data.get("version", "") or "")
            details.append(f"Manifest version: {manifest_version or '<missing>'}")
            details.append(f"Runtime version: {FBP_VERSION_STRING}")
            if manifest_version != FBP_VERSION_STRING:
                failures.append(
                    f"Version mismatch: manifest {manifest_version or '<missing>'} != runtime {FBP_VERSION_STRING}"
                )
        except (OSError, UnicodeError, tomllib.TOMLDecodeError) as exc:
            failures.append(f"Could not validate blender_manifest.toml: {exc}")

        dependency_versions = []
        for module_name in ("PIL", "psd_tools", "attrs", "typing_extensions"):
            try:
                module = importlib.import_module(module_name)
                version = str(getattr(module, "__version__", "bundled") or "bundled")
                dependency_versions.append(f"{module_name}: {version}")
            except Exception as exc:
                failures.append(f"Bundled dependency {module_name} could not be imported: {exc}")
        details.extend(dependency_versions)

        required_scene_props = (
            "fbp_experimental_compositor",
            "fbp_settings_section",
            "fbp_pending_planes",
            "fbp_layers",
        )
        for name in required_scene_props:
            if not hasattr(context.scene, name):
                failures.append(f"Required Scene property is missing: {name}")

        status = "FAIL" if failures else ("WARNING" if warnings else "PASS")
        self._record(
            "Preflight and registration",
            status,
            f"{len(operator_ids)} operators · {self._effect_count} effects · {len(failures)} failure(s)",
            tuple(details + failures + warnings),
            time.perf_counter() - started,
        )

    def _make_import_scene(self, context):
        scene = bpy.data.scenes.new("FBP Developer Import Test")
        scene["fbp_developer_test_scene"] = True
        scene.frame_start = 1
        scene.frame_end = 24
        try:
            scene.fbp_gen_camera = False
            scene.fbp_pre_duration = 2
            scene.fbp_pre_loop_mode = 'REPEAT'
            scene.fbp_pre_shadeless = True
        except FBP_DATA_ERRORS:
            pass
        context.window.scene = scene
        return scene

    def _step_import_smoke(self, context):
        started = time.perf_counter()
        scene = self._make_import_scene(context)
        root = Path(tempfile.mkdtemp(prefix="fbp_developer_test_"))
        self._temp_paths.append(str(root))
        still = _write_test_png(root / "Still.png", 1)
        for index in range(1, 4):
            _write_test_png(root / f"Walk_{index:04d}.png", index + 3)
        _write_test_png(root / "Nested" / "Background.png", 9)

        checks = []
        failures = []
        previous_count = len(_scene_rigs(scene))

        ok, _result, error, elapsed = self._run_operator(
            "fbp.import_single_image", filepath=still, directory=str(root)
        )
        current_count = len(_scene_rigs(scene))
        checks.append(f"Single image import: {'PASS' if ok and current_count > previous_count else 'FAIL'} ({elapsed:.2f}s)")
        if not ok or current_count <= previous_count:
            failures.append(error or "Single image import did not create a layer")
        previous_count = current_count

        context.window_manager.clipboard = still
        ok, _result, error, elapsed = self._run_operator("fbp.import_single_image_from_clipboard")
        current_count = len(_scene_rigs(scene))
        checks.append(f"Clipboard file-path import: {'PASS' if ok and current_count > previous_count else 'FAIL'} ({elapsed:.2f}s)")
        if not ok or current_count <= previous_count:
            failures.append(error or "Clipboard file-path import did not create a layer")
        previous_count = current_count

        ok, _result, error, elapsed = self._run_operator(
            "fbp.import_folder_multiplane",
            directory=str(root),
            preflight_ready=True,
            import_mode='AUTO',
            animation=True,
            synchronous_generation=True,
        )
        current_count = len(_scene_rigs(scene))
        checks.append(f"Folder auto-detect import: {'PASS' if ok and current_count > previous_count else 'FAIL'} ({elapsed:.2f}s)")
        if not ok or current_count <= previous_count:
            failures.append(error or "Folder import did not create layers")
        previous_count = current_count

        context.window_manager.clipboard = f'"{root}"'
        ok, _result, error, elapsed = self._run_operator(
            "fbp.import_folder_multiplane",
            directory="",
            from_clipboard=True,
            preflight_ready=True,
            import_mode='AUTO',
            animation=True,
            synchronous_generation=True,
        )
        current_count = len(_scene_rigs(scene))
        checks.append(f"Clipboard folder import: {'PASS' if ok and current_count > previous_count else 'FAIL'} ({elapsed:.2f}s)")
        if not ok or current_count <= previous_count:
            failures.append(error or "Clipboard folder import did not create layers")

        for plane_type in ('CUSTOM', 'GRADIENT', 'HOLDOUT'):
            before = len(_scene_rigs(scene))
            ok, _result, error, elapsed = self._run_operator(
                "fbp.create_color_plane", plane_type=plane_type
            )
            after = len(_scene_rigs(scene))
            checks.append(f"{plane_type.title()} plane operator: {'PASS' if ok and after > before else 'FAIL'} ({elapsed:.2f}s)")
            if not ok or after <= before:
                failures.append(error or f"{plane_type} plane was not created")

        rigs = _scene_rigs(scene)
        backends = {}
        for rig in rigs:
            backend = fbp_layer_backend_type(rig)
            backends[backend] = backends.get(backend, 0) + 1
        checks.append(f"Generated smoke-test layers: {len(rigs)}")
        checks.extend(f"Backend {key}: {value}" for key, value in sorted(backends.items()))

        self._record(
            "Import and creation smoke test",
            "FAIL" if failures else "PASS",
            f"{len(rigs)} generated layer(s) · {len(failures)} failure(s)",
            tuple(checks + failures),
            time.perf_counter() - started,
        )

    def _step_import_contracts(self, context):
        started = time.perf_counter()
        scene = context.window.scene
        details = []
        failures = []
        warnings = []
        for idname, kwargs, label in (
            ("fbp.project_health_check", {}, "Project Health"),
            ("fbp.repair_all_layer_relations", {}, "Layer relation repair"),
            ("fbp.repair_effect_controls", {}, "Effect control repair"),
            ("fbp.run_lifecycle_audit", {"repair": False}, "Lifecycle Audit"),
            ("fbp.run_native_backend_regression", {"repair": False, "probe_timeline": True}, "Native Backend Regression"),
            ("fbp.deep_addon_audit", {"repair": False}, "Deep Add-on Audit"),
        ):
            ok, _result, error, elapsed = self._run_operator(idname, **kwargs)
            details.append(f"{label}: {'FINISHED' if ok else 'FAILED'} ({elapsed:.2f}s)")
            if not ok:
                failures.append(error or f"{label} did not finish")

        for label, report_name in (
            ("Import Project Health", "FBP_Project_Health"),
            ("Import Lifecycle", "FBP_Lifecycle_Audit"),
            ("Import Native Contracts", "FBP_Native_Backend_Regression"),
            ("Import Deep Audit", "FBP_Deep_Addon_Audit"),
        ):
            text = bpy.data.texts.get(report_name)
            status = diagnostic_report_status(text)
            messages = diagnostic_report_messages(text)
            details.append(f"{label}: {status}")
            if status == "FAIL" and messages:
                failures.extend(f"{label}: {item}" for item in messages)
            elif status == "WARNING" and messages:
                warnings.extend(f"{label}: {item}" for item in messages)

        status = "FAIL" if failures else ("WARNING" if warnings else "PASS")
        self._record(
            "Import-scene contracts",
            status,
            f"{len(_scene_rigs(scene))} layer(s) audited · {len(failures)} failure(s) · {len(warnings)} warning(s)",
            tuple(details + failures[:100] + warnings[:100]),
            time.perf_counter() - started,
        )

    def _step_native_regression(self, context):
        ok, _result, error, elapsed = self._run_operator(
            "fbp.create_native_regression_scene", replace_existing=True
        )
        if error:
            self._record("Native regression scene operator", "FAIL", error, duration=elapsed)
        self._capture_report(
            "Native regression scene",
            "FBP_Native_Regression_Scene_Report",
            operator_ok=ok,
            duration=elapsed,
        )
        if not ok:
            return
        scene = context.window.scene
        scene["fbp_developer_test_scene"] = True

        ok, _result, error, elapsed = self._run_operator(
            "fbp.run_native_backend_regression", repair=False, probe_timeline=True
        )
        if error:
            self._record("Native backend operator", "FAIL", error, duration=elapsed)
        self._capture_report(
            "Native backend regression",
            "FBP_Native_Backend_Regression",
            operator_ok=ok,
            duration=elapsed,
        )

    def _step_native_persistence_parity(self, context):
        scene = context.window.scene
        if not bool(scene.get("fbp_native_regression_scene", False)):
            self._record("Native persistence and parity", "FAIL", "Native regression Scene is not active")
            return

        details = []
        failures = []
        warnings = []
        ok, _result, error, elapsed = self._run_operator(
            "fbp.run_persistence_audit", action='CAPTURE', require_reopen=False
        )
        details.append(f"Persistence capture: {'PASS' if ok else 'FAIL'} ({elapsed:.2f}s)")
        if not ok:
            failures.append(error or "Persistence baseline capture failed")
        ok_verify, _result, error, elapsed_verify = self._run_operator(
            "fbp.run_persistence_audit", action='VERIFY', require_reopen=False
        )
        details.append(f"Same-session semantic verification: {'PASS' if ok_verify else 'FAIL'} ({elapsed_verify:.2f}s)")
        if not ok_verify:
            failures.append(error or "Persistence same-session verification failed")
        persistence_text = bpy.data.texts.get("FBP_Persistence_Audit")
        persistence_status = diagnostic_report_status(persistence_text)
        persistence_messages = diagnostic_report_messages(persistence_text)
        details.append(f"Persistence report: {persistence_status}")
        if persistence_status == "FAIL" and persistence_messages:
            failures.extend(persistence_messages)
        elif persistence_status == "WARNING" and persistence_messages:
            warnings.extend(persistence_messages)

        ok_parity, _result, error, parity_elapsed = self._run_operator(
            "fbp.run_render_parity_audit",
            resolution=64,
            cycles_samples=1,
            include_compositor=False,
            keep_images=False,
            strict=False,
            require_both_engines=False,
        )
        if error:
            failures.append(f"Render parity operator: {error}")
        parity_text = bpy.data.texts.get("FBP_Render_Parity_Audit")
        parity_status = diagnostic_report_status(parity_text)
        parity_messages = diagnostic_report_messages(parity_text)
        details.append(f"Eevee/Cycles parity: {parity_status} ({parity_elapsed:.2f}s)")
        if not ok_parity or parity_status == "FAIL":
            failures.extend(parity_messages or ("Eevee/Cycles parity did not pass",))
        elif parity_status == "WARNING":
            warnings.extend(parity_messages or ("Eevee/Cycles parity was incomplete",))

        status = "FAIL" if failures else ("WARNING" if warnings else "PASS")
        self._record(
            "Native persistence and parity",
            status,
            f"Persistence {persistence_status} · render parity {parity_status}",
            tuple(details + failures[:100] + warnings[:100]),
            elapsed + elapsed_verify + parity_elapsed,
        )

    def _step_compositor(self, context):
        started = time.perf_counter()
        details = []
        failures = []
        try:
            from .compositor import fbp_scene_compositor_state
        except Exception as exc:
            self._record("Experimental compositor", "FAIL", f"Compositor module unavailable: {exc}")
            return

        scene = context.window.scene
        initial_state = fbp_scene_compositor_state(scene)
        details.append(f"Initial state: {initial_state}")
        ok, _result, error, elapsed = self._run_operator("fbp.enable_compositor")
        details.append(f"Enable: {'PASS' if ok else 'FAIL'} ({elapsed:.2f}s)")
        if not ok:
            failures.append(error or "Could not enable compositor")
        if fbp_scene_compositor_state(scene) != 'ACTIVE':
            failures.append("Compositor did not become ACTIVE")

        for preset in ('CLEAN', 'FILM', 'DREAM', 'ANIME', 'VHS'):
            ok, _result, error, elapsed = self._run_operator(
                "fbp.apply_compositor_preset", preset=preset
            )
            details.append(f"Preset {preset}: {'PASS' if ok else 'FAIL'} ({elapsed:.2f}s)")
            if not ok:
                failures.append(error or f"Preset {preset} failed")

        ok, _result, error, elapsed = self._run_operator("fbp.rebuild_compositor")
        details.append(f"Rebuild: {'PASS' if ok else 'FAIL'} ({elapsed:.2f}s)")
        if not ok:
            failures.append(error or "Compositor rebuild failed")
        ok, _result, error, elapsed = self._run_operator("fbp.restore_compositor")
        details.append(f"Restore: {'PASS' if ok else 'FAIL'} ({elapsed:.2f}s)")
        if not ok:
            failures.append(error or "Compositor restore failed")
        if fbp_scene_compositor_state(scene) == 'ACTIVE':
            failures.append("Compositor remained ACTIVE after restore")

        self._record(
            "Experimental compositor",
            "FAIL" if failures else "PASS",
            f"All presets exercised · {len(failures)} failure(s)",
            tuple(details + failures),
            time.perf_counter() - started,
        )

    def _step_effects_regression(self, context):
        ok, _result, error, elapsed = self._run_operator(
            "fbp.create_effect_regression_scene", replace_existing=True
        )
        if error:
            self._record("Effects regression operator", "FAIL", error, duration=elapsed)
        self._capture_report(
            "Effects regression scene",
            "FBP_Effects_Regression_Report",
            operator_ok=ok,
            duration=elapsed,
            info_is_pass=True,
        )
        if ok:
            scene = context.window.scene
            scene["fbp_developer_test_scene"] = True
            active_effect_ids = set()
            try:
                from .geometry_nodes import fbp_effect_ids_for_rig
                for rig in _scene_rigs(scene):
                    active_effect_ids.update(fbp_effect_ids_for_rig(rig))
            except Exception as exc:
                self._record("Effect coverage discovery", "WARNING", f"Could not enumerate generated effects: {exc}")
                return
            missing = sorted(set(FBP_EFFECT_REGISTRY) - active_effect_ids)
            self._record(
                "Registered effect coverage",
                "FAIL" if missing else "PASS",
                f"{len(active_effect_ids)}/{len(FBP_EFFECT_REGISTRY)} registered effects instantiated",
                tuple(f"Not instantiated: {effect_id}" for effect_id in missing),
            )

    def _step_effect_contracts(self, context):
        started = time.perf_counter()
        operations = (
            ("fbp.repair_all_layer_relations", {}, "Repair layer relations", None),
            ("fbp.repair_effect_controls", {}, "Repair effect controls", None),
            ("fbp.run_lifecycle_audit", {"repair": False}, "Lifecycle Audit", "FBP_Lifecycle_Audit"),
            ("fbp.run_effects_contract_audit", {"repair": False}, "Effects Contract Audit", "FBP_Effects_Contract_Audit"),
            ("fbp.run_mask_interaction_audit", {"repair": False}, "Mask Interaction Audit", "FBP_Mask_Interaction_Audit"),
            ("fbp.run_render_contract_audit", {"repair": False}, "Render Contract Audit", "FBP_Render_Contract_Audit"),
            ("fbp.deep_addon_audit", {"repair": False}, "Deep Add-on Audit", "FBP_Deep_Addon_Audit"),
        )
        details = []
        failures = []
        warnings = []
        for idname, kwargs, label, report_name in operations:
            ok, _result, error, elapsed = self._run_operator(idname, **kwargs)
            details.append(f"{label}: {'FINISHED' if ok else 'FAILED'} ({elapsed:.2f}s)")
            if not ok:
                failures.append(error or f"{label} did not finish")
            if report_name:
                status = diagnostic_report_status(bpy.data.texts.get(report_name))
                messages = diagnostic_report_messages(bpy.data.texts.get(report_name))
                details.append(f"{label} report: {status}")
                if status == "FAIL" and messages:
                    failures.extend(f"{label}: {item}" for item in messages)
                elif status == "WARNING" and messages:
                    warnings.extend(f"{label}: {item}" for item in messages)
        status = "FAIL" if failures else ("WARNING" if warnings else "PASS")
        self._record(
            "Effects, masks and render contracts",
            status,
            f"{len(_scene_rigs(context.window.scene))} layer(s) · {len(failures)} failure(s) · {len(warnings)} warning(s)",
            tuple(details + failures[:150] + warnings[:150]),
            time.perf_counter() - started,
        )

    def _step_profile(self, context):
        ok, _result, error, elapsed = self._run_operator("fbp.profile_effects", samples=3)
        if error:
            self._record("Effects profiler operator", "FAIL", error, duration=elapsed)
        self._capture_report(
            "Performance profile",
            "FBP_Effects_Profiler_Report",
            operator_ok=ok,
            duration=elapsed,
            info_is_pass=True,
        )

    def _step_release_gate(self, context):
        ok, _result, error, elapsed = self._run_operator(
            "fbp.run_release_gate",
            require_native_layers=True,
            require_zero_warnings=True,
            require_persistence_verification=False,
            require_undo_redo_verification=False,
            require_render_parity_verification=False,
        )
        if error:
            self._record("Release Gate operator", "FAIL", error, duration=elapsed)
        self._capture_report(
            "Automated release gate",
            "FBP_Release_Gate",
            operator_ok=ok,
            duration=elapsed,
        )

    def _step_clipboard_diagnostic(self, context):
        started = time.perf_counter()
        ok, _result, error, _elapsed = self._run_operator(
            "fbp.copy_diagnostic_messages",
            report_name="FBP_Release_Gate",
            full_report=True,
        )
        clipboard = str(getattr(context.window_manager, "clipboard", "") or "")
        valid = ok and "Frame By Plane — Release Gate" in clipboard
        self._record(
            "Clipboard diagnostic path",
            "PASS" if valid else "FAIL",
            "Existing diagnostic report copied successfully" if valid else "Diagnostic clipboard copy failed",
            (() if valid else (error or "Clipboard did not contain the complete Release Gate report",)),
            time.perf_counter() - started,
        )

    def _restore_original_context(self, context):
        window = getattr(context, "window", None)
        original = self._original_scene
        if window is not None and original is not None:
            try:
                if bpy.data.scenes.get(original.name) == original:
                    window.scene = original
                    original.frame_set(self._original_frame)
            except FBP_DATA_ERRORS:
                pass
        try:
            bpy.ops.object.select_all(action='DESELECT')
        except (AttributeError, RuntimeError):
            pass
        if original is not None:
            for name in self._original_selected_names or ():
                obj = original.objects.get(name)
                if obj is not None:
                    try:
                        obj.select_set(True)
                    except FBP_DATA_ERRORS:
                        pass
            active = self._original_active_object
            try:
                if active is not None and original.objects.get(active.name) == active:
                    context.view_layer.objects.active = active
            except FBP_DATA_ERRORS:
                pass
        # Re-enter only the common editable modes; unusual modes are left in
        # Object mode rather than risking a context-sensitive restoration error.
        mode_map = {
            "EDIT_MESH": "EDIT",
            "EDIT_CURVE": "EDIT",
            "EDIT_SURFACE": "EDIT",
            "EDIT_ARMATURE": "EDIT",
            "SCULPT": "SCULPT",
            "PAINT_WEIGHT": "WEIGHT_PAINT",
            "PAINT_VERTEX": "VERTEX_PAINT",
            "PAINT_TEXTURE": "TEXTURE_PAINT",
        }
        target_mode = mode_map.get(self._original_mode)
        if target_mode:
            try:
                if bpy.ops.object.mode_set.poll():
                    bpy.ops.object.mode_set(mode=target_mode)
            except (AttributeError, RuntimeError):
                pass

    def _remove_new_data(self):
        # Shape Mask caches and deferred mutation closures can contain names or
        # RNA wrappers derived from temporary Scenes. Retire both before freeing
        # IDs so nothing can resume against an obsolete Scene graph.
        try:
            from .object_masks import clear_object_mask_runtime_cache
            clear_object_mask_runtime_cache()
        except (ImportError, AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
            pass
        try:
            from .safe_tasks import clear_scheduled
            clear_scheduled()
        except (ImportError, AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
            pass

        # Remove test Scenes first so their owned collections are detached.
        original_scene_ptr = _id_pointer(self._original_scene) if self._original_scene is not None else None
        scene_snapshot = self._data_snapshot.get("scenes", set())
        for scene in tuple(bpy.data.scenes):
            pointer = _id_pointer(scene)
            if pointer in scene_snapshot or pointer == original_scene_ptr:
                continue
            try:
                bpy.data.scenes.remove(scene)
            except FBP_DATA_ERRORS:
                pass

        # Explicitly unlink every newly-created Object, even when generated
        # PointerProperties or collection links still report users. Shape Mask
        # helpers are removed first so no child retains a parent reference while
        # its generated plane/rig is freed.
        object_snapshot = self._data_snapshot.get("objects", set())
        new_objects = [
            item for item in tuple(bpy.data.objects)
            if _id_pointer(item) not in object_snapshot
        ]
        def _object_cleanup_priority(item):
            try:
                return 0 if bool(item.get("fbp_is_object_mask_helper", False)) else 1
            except FBP_DATA_ERRORS:
                return 1
        new_objects.sort(key=_object_cleanup_priority)
        for item in new_objects:
            try:
                bpy.data.objects.remove(item, do_unlink=True)
            except FBP_DATA_ERRORS:
                pass

        # Remove generated Collections after their Objects. Multiple passes deal
        # with nested children whose user counts fall only after a parent is freed.
        collection_snapshot = self._data_snapshot.get("collections", set())
        for _pass in range(4):
            changed = False
            for item in tuple(bpy.data.collections):
                if _id_pointer(item) in collection_snapshot:
                    continue
                try:
                    bpy.data.collections.remove(item, do_unlink=True)
                    changed = True
                except FBP_DATA_ERRORS:
                    continue
            if not changed:
                break

        # Remaining generated datablocks are safe to remove once no Object uses
        # them. Text cleanup remains restricted to known diagnostic names.
        for _pass in range(4):
            changed = False
            for name in _CLEANUP_COLLECTIONS:
                if name in {"objects", "collections"}:
                    continue
                collection = getattr(bpy.data, name, None)
                if collection is None:
                    continue
                before = self._data_snapshot.get(name, set())
                for item in tuple(collection):
                    if _id_pointer(item) in before:
                        continue
                    try:
                        users = int(getattr(item, "users", 0) or 0)
                    except FBP_DATA_ERRORS:
                        continue
                    if name == "texts":
                        item_name = str(getattr(item, "name", "") or "")
                        is_test_text = (
                            item_name in _INTERMEDIATE_REPORT_NAMES
                            or item_name.startswith("FBP_Persistence_Baseline")
                            or item_name == _REPORT_NAME
                        )
                        if not is_test_text:
                            continue
                    elif users > 0:
                        continue
                    try:
                        collection.remove(item)
                        changed = True
                    except FBP_DATA_ERRORS:
                        continue
            if not changed:
                break

        try:
            from .object_masks import clear_object_mask_runtime_cache
            clear_object_mask_runtime_cache()
        except (ImportError, AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
            pass

    def _restore_scene_names(self):
        for scene, original_name in reversed(self._scene_backups or ()):
            try:
                if scene.name in bpy.data.scenes:
                    occupant = bpy.data.scenes.get(original_name)
                    if occupant is not None and occupant != scene:
                        bpy.data.scenes.remove(occupant)
                    scene.name = original_name
            except FBP_DATA_ERRORS:
                pass

    def _restore_intermediate_reports(self):
        for name, state in (self._report_snapshot or {}).items():
            text = bpy.data.texts.get(name)
            if state is None:
                if text is not None:
                    try:
                        bpy.data.texts.remove(text)
                    except FBP_DATA_ERRORS:
                        pass
                continue
            content, fake_user = state
            if text is None:
                text = bpy.data.texts.new(name)
            try:
                text.clear()
                text.write(content)
                text.use_fake_user = bool(fake_user)
            except FBP_DATA_ERRORS:
                pass

    def _build_final_report(self):
        total_elapsed = time.perf_counter() - self._start_time
        failures = [record for record in self._records if record["status"] == "FAIL"]
        warnings = [record for record in self._records if record["status"] == "WARNING"]
        passes = [record for record in self._records if record["status"] == "PASS"]
        overall = "FAIL" if failures else ("WARNING" if warnings or self._cancelled else "PASS")
        lines = [
            "Frame By Plane — Autonomous Developer Test",
            "===========================================",
            f"Generated: {datetime.now().isoformat(timespec='seconds')}",
            f"Frame By Plane: {FBP_VERSION_STRING}",
            f"Blender: {bpy.app.version_string}",
            f"Platform: {platform.platform()}",
            f"Python: {platform.python_version()}",
            f"Duration: {total_elapsed:.2f} seconds",
            f"Result: {overall}",
            "",
            "Coverage summary",
            "----------------",
            f"Registered FBP operators discovered: {self._operator_count}",
            f"Registered effects: {self._effect_count}",
            f"Passed sections: {len(passes)}",
            f"Warning sections: {len(warnings)}",
            f"Failed sections: {len(failures)}",
            f"Operator poll exceptions: {len(self._poll_errors or ())}",
            "",
            "Automated sections",
            "------------------",
        ]
        for index, record in enumerate(self._records, 1):
            duration = f" · {record['duration']:.2f}s" if record["duration"] > 0.0 else ""
            lines.append(f"{index:02d}. [{record['status']}] {record['name']} — {record['summary']}{duration}")
            for detail in record["details"]:
                lines.append(f"    - {detail}")

        lines.extend((
            "",
            "Manual release checks still required",
            "------------------------------------",
        ))
        lines.extend(f"- {item}" for item in _MANUAL_CHECKS)
        lines.extend((
            "",
            "Interpretation",
            "--------------",
            "PASS means the autonomous synthetic regression suite completed without a detected blocker.",
            "WARNING means the suite completed but found a non-blocking diagnostic or was cancelled.",
            "FAIL means at least one automated section found a blocker or could not complete.",
            "Manual checks are intentionally excluded from the automated result and must be completed before a public release.",
            "",
            "Result",
            "------",
            overall,
        ))
        return lines, overall

    def _finish(self, context):
        if self._finished:
            return
        self._finished = True
        # Keep all managed timers paused until every temporary ID and report has
        # been finalized. The finally block guarantees recovery after any cleanup
        # or clipboard error and adds one idle event-loop grace period.
        fbp_runtime_set("fbp_pause_managed_timers", True)
        try:
            self._finish_impl(context)
        finally:
            try:
                from .safe_tasks import clear_scheduled
                clear_scheduled()
            except (ImportError, AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
                pass
            try:
                from .object_masks import clear_object_mask_runtime_cache
                clear_object_mask_runtime_cache()
            except (ImportError, AttributeError, ReferenceError, RuntimeError, TypeError, ValueError):
                pass
            try:
                wm = getattr(context, "window_manager", None)
                if wm is not None:
                    wm.fbp_developer_test_running = False
            except FBP_DATA_ERRORS:
                pass
            fbp_runtime_set("fbp_managed_timers_resume_after", time.monotonic() + 1.0)
            fbp_runtime_set("fbp_pause_managed_timers", False)

    def _finish_impl(self, context):
        wm = getattr(context, "window_manager", None)
        if self._timer is not None and wm is not None:
            try:
                wm.event_timer_remove(self._timer)
            except (ReferenceError, RuntimeError):
                pass
            self._timer = None

        # The original Scene must be active before generated Scenes are removed.
        self._restore_original_context(context)
        self._remove_new_data()
        self._restore_scene_names()
        self._restore_intermediate_reports()
        for path in self._temp_paths or ():
            try:
                shutil.rmtree(path, ignore_errors=True)
            except OSError:
                pass

        lines, overall = self._build_final_report()
        original_scene = self._original_scene
        text = write_diagnostic_report(
            original_scene,
            _REPORT_NAME,
            lines,
            summary=f"Developer Tool · {overall}",
            status="PASS" if overall == "PASS" else "WARNING",
        )
        report_text = "\n".join(lines) if text is None else _safe_text_string(text)
        clipboard_ok = True
        try:
            context.window_manager.clipboard = report_text
        except FBP_DATA_ERRORS as exc:
            fbp_warn("Could not copy the Developer Tool report", exc)
            clipboard_ok = False
            overall = "FAIL"
            lines.extend((
                "",
                "Clipboard error",
                "---------------",
                f"{type(exc).__name__}: {exc}",
            ))
            text = write_diagnostic_report(
                original_scene,
                _REPORT_NAME,
                lines,
                summary="Developer Tool · FAIL",
                status="WARNING",
            )

        if wm is not None:
            wm.fbp_developer_test_running = False
            wm.fbp_developer_test_progress = 1.0
            wm.fbp_developer_test_step = int(getattr(wm, "fbp_developer_test_total", 0) or 0)
            wm.fbp_developer_test_status = (
                f"{overall} · report copied to clipboard"
                if clipboard_ok else "FAIL · report saved in Blender Text Editor"
            )
            wm.fbp_developer_test_last_status = overall
        _tag_redraw()
        self.report(
            {'INFO'} if overall == "PASS" else {'WARNING'},
            (
                f"Developer Tool {overall} — report copied to clipboard"
                if clipboard_ok else "Developer Tool FAIL — report saved in Blender Text Editor"
            ),
        )

    def cancel(self, context):
        self._cancelled = True
        self._finish(context)


_CLASSES = (FBP_OT_RunAutonomousDeveloperTest,)


def _register_properties():
    bpy.types.WindowManager.fbp_developer_tool_unlocked = BoolProperty(
        name="Unlock Developer Tool",
        description=(
            "Unlock the autonomous Developer Tool for one run. The lock closes automatically when the test starts"
        ),
        default=False,
        options={'SKIP_SAVE'},
    )
    bpy.types.WindowManager.fbp_developer_test_running = BoolProperty(
        name="Developer Test Running",
        default=False,
        options={'HIDDEN', 'SKIP_SAVE'},
    )
    bpy.types.WindowManager.fbp_developer_test_progress = FloatProperty(
        name="Developer Test Progress",
        default=0.0,
        min=0.0,
        max=1.0,
        subtype='FACTOR',
        options={'HIDDEN', 'SKIP_SAVE'},
    )
    bpy.types.WindowManager.fbp_developer_test_step = IntProperty(
        name="Developer Test Step",
        default=0,
        min=0,
        options={'HIDDEN', 'SKIP_SAVE'},
    )
    bpy.types.WindowManager.fbp_developer_test_total = IntProperty(
        name="Developer Test Total",
        default=0,
        min=0,
        options={'HIDDEN', 'SKIP_SAVE'},
    )
    bpy.types.WindowManager.fbp_developer_test_status = StringProperty(
        name="Developer Test Status",
        default="",
        options={'HIDDEN', 'SKIP_SAVE'},
    )
    bpy.types.WindowManager.fbp_developer_test_last_status = StringProperty(
        name="Developer Test Last Status",
        default="NOT_RUN",
        options={'HIDDEN', 'SKIP_SAVE'},
    )


def _unregister_properties():
    for name in (
        "fbp_developer_tool_unlocked",
        "fbp_developer_test_running",
        "fbp_developer_test_progress",
        "fbp_developer_test_step",
        "fbp_developer_test_total",
        "fbp_developer_test_status",
        "fbp_developer_test_last_status",
    ):
        try:
            delattr(bpy.types.WindowManager, name)
        except FBP_DATA_IO_ERRORS:
            pass


def register():
    for cls in _CLASSES:
        bpy.utils.register_class(cls)
    _register_properties()


def unregister():
    _unregister_properties()
    for cls in reversed(_CLASSES):
        try:
            bpy.utils.unregister_class(cls)
        except FBP_DATA_IO_ERRORS:
            pass
